// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyrqcmjfewlpwalqjmgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cnFjbWpmZXdscHdhbHFqbWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMjAyMDcsImV4cCI6MjA1NzY5NjIwN30.y0dsLpOyNSkrHwC7WZvfaF5sK45cscnH0Bk7Z8gkgRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);